services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin


volumes:
  postgres-data:
