apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:10.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgres-volume
              mountPath: /etc/config
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-config
      restartPolicy: Always

      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pv-volume
