apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-admin
  labels:
    app: db-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-admin
  template:
    metadata:
      name: db-admin
      labels:
        app: db-admin
    spec:
      containers:
        - name: db-admin
          image: adminer:4.7.6-standalone
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: db-adminer-configmap
      restartPolicy: Always
      
