apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30950
        hostPort: 8080
      - containerPort: 30951
        hostPort: 8081
  - role: worker
  - role: worker
