name: Dcoker FE 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-fe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build and deply FE
      run: |
        cd cc_fe
        npm install -g @angular/cli
        npm install
        cd cc_fe
        ng build

    - name: Build Docker image for Microservice 1
      run: |
        docker build -t alexandrudaniel/cc_fe:latest

    - name: Push Docker image to Docker Hub for Fe
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push alexandrudaniel/cc_fe:latest
